OPENAI_API_KEY = "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"
ASSISTANT_ID = "asst_YZrJxpGw9UCgsDg1pGQ4IVAZ"